### ISSUE TITLE
Add support for cost tracking and limiting

### ISSUE THREAD

**Issue by underbluewaters** [mcclintock-lab/seasketch-sls-geoprocessing#59]

**Comment by underbluewaters** [comment]
- [x] Add schema for setting monthly spend limits
- [x] Add spend information to projects endpoint
- [x] Add admin interface to adjust spend limit
- [ ] check budget at invocation time, and include proper [rate-limiting headers](https://stackoverflow.com/questions/16022624/examples-of-http-api-rate-limiting-http-response-headers)
